### ISSUE TITLE
Adding a global Swedish GTFS collection

### ISSUE THREAD

**Issue by Venefilyn** [osm-ToniE/gtfs-feeds#30]
Hey @osm-ToniE,

We have a GTFS collection that covers all public transports in Sweden, from their [about me](https://www.trafiklab.se/about/)

> Trafiklab is a service developed and managed by Samtrafiken on behalf of the regional public transport authorities in Sweden.

Could you add [GTFS Sverige 2](https://www.trafiklab.se/api/trafiklab-apis/gtfs-sverige-2/)? It's [licensed under CC0 1.0](https://www.trafiklab.se/api/trafiklab-apis/gtfs-sverige-2/licence/)

**Comment by Venefilyn** [comment]
Thanks! I've reached out to TrafikLab as well to hear what they can offer

**Comment by Venefilyn** [comment]
Hey @osm-ToniE! 

I reached out to [TrafikLab here who has now responded](https://support.trafiklab.se/org/trafiklabse/d/oppet-eller-mer-tillgangligt-api-for-gtfs-sverige-/). In short, they have been doing a lot of improvements which is why it took so long. But they do have an [archive service that offers the data from the last iteration](https://data.samtrafiken.se/trafiklab/gtfs-sverige-2/). If you check the dates of the data it should be updated once per day, which is how often they update the live data that you need an API key for

So can probably make use of that archive service to get data into GTFS

**Comment by Bertware** [comment]
@Venefilyn is it an option for you to create an API key and update @osm-ToniE when changes to the URL/format are made? In that case, you could provide a GTFS link. Since you're driving this integration forward, it's also up to you to pick the most suitable feed for this analysis.

Alternatively, you could use the historic data for GTFS Sverige 2, our old dataflow, as it probably isn't crucial if a stop pops up one day later. The most important downside would be only having information at stop area level, and missing information about quays. If this is enough, looking at the scripting structure, one could test if a file exists for yesterdays date in the get-release-date script. The archive is accessible at https://data.samtrafiken.se/trafiklab/gtfs-sverige-2/2024/10/. 

If you are also interested in shapes, these can be found in our new feeds. Updates are automated, and take place every night. This could be scripted as well in the update script, which would remove the need for a HEAD request with API key. Note that some cross-county routes or trips may occur twice in our GTFS Sweden 3 data, something we are aware of and working to improve.

**Comment by osm-ToniE** [comment]
Thanks for the information.

From PTNA's point of view there is no problem using feeds from the archive. PTNA anyway downloads only the first available dataset of a month, checking is done on a daily basis though (some operators only update every now and then, not on a regular basis). I'll configure that over the weekend
The algorithm will be something like:

```
YEAR=$(date +%Y)
MONTH=$(date +%m)
wget -O - https://data.samtrafiken.se/trafiklab/gtfs-sverige-2/$YEAR/$MONTH/  | \
grep sweden | \
tail -1 | \
sed -e 's/...../...../'
```
for both: get the URL and get the release date.

However, the comparison of [OSM with GTFS](https://ptna.openstreetmap.de/gtfs/compare-routes.php?feed=US-NY-MTA-Subway&release_date=&route_id=3&relation=9663807) data should be done using "quay" data (GTFS term 'pole'?), not stop area data.
GTFS routes are compared with OSM route_masters (see link above).
GTFS trips are compared with OSM routes: [example](https://ptna.openstreetmap.de/gtfs/compare-trips.php?feed=US-NY-MTA-Subway&release_date=&trip_id=ASP24GEN-3091-Weekday-00_030150_3..S01R&relation=9663806) based on 'name' and 'lat/lon' of GTFS stops and OSM platforms.

So, the mid-term goal should be having access to and analysing "GTFS Sweden 3" data.

**Comment by osm-ToniE** [comment]
Just added "GTFS Sweden 2" data

**Comment by Venefilyn** [comment]
Awesome work, thanks @osm-ToniE! And thank you @Bertware for helping out :pray: 

I can register and get an apiKey for you @osm-ToniE, lmk where to send it to. As for checking if the API for GTFS Sweden 3 has a newer "last-modified". Given they update it once a day for [the static data](https://www.trafiklab.se/api/gtfs-datasets/gtfs-sweden/#static-data) it shouldn't be an issue right?

**Comment by osm-ToniE** [comment]
> I can register and get an apiKey for you

Great!

Is it OK for you if I store the API key as ENV variable in ~/.profile on the server?
It is a hosted server (at Hetzner in Finland?), maintained by some sys-admins of [FOSSGIS](https://www.fossgis.de/), an association also acting as the local German chapter of OSM, owner of the openstreetmap.de domain.

>  lmk where to send it to

osm-ToniE@web.de is fine.

> As for checking if the API for GTFS Sweden 3 has a newer "last-modified". Given they update it once a day for [the static data](https://www.trafiklab.se/api/gtfs-datasets/gtfs-sweden/#static-data) it shouldn't be an issue right?

No problem at all.

**Comment by Venefilyn** [comment]
Done. API sent to the email. Having it stored in the server in an envar is fine

**Comment by osm-ToniE** [comment]
Thanks and it seems to work using also `--header "Accept-Encoding: gzip"`.
This also allows using HEAD request, which then provides `last-modified` header (for the release date).

**Comment by osm-ToniE** [comment]
@Bertware @Venefilyn 

I found some oddities using the "GTFS Sweden 3" data:
- route_ids, trip_ids, stop_ids, shape_ids, agency_ids differ from the other "GTFS Sweden 2"
  - OK, no issue
- PTNA's aggregation [blows the DB up from 6GB to 8GB](https://ptna.openstreetmap.de/en/gtfs-details.php?feed=SE-Samtrafiken#gtfs-ptna-aggregation-table)
  - usually the DB shrinks by a factor of about 5
  - this seems to be due to the fact that each trip_id has its own shape_id:
  - [Bus 1 Hallandstrafiken](https://ptna.openstreetmap.de/gtfs/SE/trips.php?feed=SE-Samtrafiken&release_date=&route_id=9011013120100000) - [trip example 1 starts at 5:30](https://ptna.openstreetmap.de/gtfs/SE/single-trip.php?feed=SE-Samtrafiken&release_date=&trip_id=131300000000002060) and [trip example 2 starts at 7:06](https://ptna.openstreetmap.de/gtfs/SE/single-trip.php?feed=SE-Samtrafiken&release_date=&trip_id=131300000000007548), **same bus, same route**, 1:1 relationship between trip_id and shape_id
  - for a shape_id there usually should be a 1:n relationship :n-trips follow 1 shape
  - so: not only PTNA's DB is huge, the original data is unnecessarily huge as well, could be clearly reduced in shapes.txt
  - see the [same bus in "GTFS Sweden 2" data](https://ptna.openstreetmap.de/gtfs/SE/trips.php?feed=SE-Samtrafiken&release_date=&route_id=1261120100001) (w/o shapes of course) where PTNA reduces/aggregates the trips to 2 representative trips. We should see the same short list also for "GTFS Sweden 3"
    - aggregation in PTNA means: summarize all trips of a route with same stop sequence to a single one
      - they differ only in start time, PTNA is not interested in start times at the moment

Let's also see with the next GTFS version, whether the route_ids, trip_ids, agency_ids, shape_ids, stop_ids change completely or whether they stay stable from version to version.
- changing IDs are a huge/crucial impediment for using these GTFS data for QA, ... in OSM

**Comment by Brickblock1** [comment]
Based on my experience with the gtfs regional datasets which are similar I would expect ids to stay fixed it is however a bit odd that shapes don't work as expected since they work just fine with the regional ones

**Comment by osm-ToniE** [comment]
Actually a 1:1 relationship between trip_id and shape_id is not a bug. Everything works fine but the DB is huge.

**Comment by osm-ToniE** [comment]
> changing IDs are a huge/crucial impediment for using these GTFS data for QA, ... in OSM

It seems that route_id and trip_id stay the same from one GTFS feed to the other

- [Bus 57 AB Storstockholms Lokaltrafik](https://ptna.openstreetmap.de/gtfs/compare-routes.php?feed=SE-Samtrafiken&feed2=SE-Samtrafiken&release_date=2024-10-22&release_date2=2024-10-20&route_id=9011001005700000&route_id2=9011001005700000) - might take a few seconds
  - the bold number "0.10%" indicates a small difference between the trips, but trip_id is the same
  - the bold number "0.00%" indicates identical trips with same trip_id

- [Complete comparison of two GTFS feeds](https://ptna.openstreetmap.de/gtfs/compare-versions.php?feed=SE-Samtrafiken&release_date=2024-10-22&release_date2=2024-10-20) - might take some time
  - comparing two routes with high number of variants will take lots of time
  - high number of variants might be caused by 1:1 relationship trip_id:shape:id
    - [cmp Bus 150 Blekingetrafiken](https://ptna.openstreetmap.de/gtfs/compare-routes.php?feed=SE-Samtrafiken&feed2=SE-Samtrafiken&release_date=2024-10-22&release_date2=2024-10-20&route_id=9011010015000000&route_id2=9011010015000000)
    - [Bus 150 Blekingetrafiken](https://ptna.openstreetmap.de/gtfs/SE/trips.php?feed=SE-Samtrafiken&release_date=&route_id=9011010015000000)

All-in-all: 1:1 relationship between trip_id:shape_id is no good for comparison of two GTFS feeds
